export type Locale = "sr" | "en" | "de";

export const locales: Locale[] = ["sr", "en", "de"];

export const copy = {
  sr: {
    nav: { work: "Rad", process: "Proces", booking: "Termini", reserve: "Rezervisi" },
    heroLine: "Ink is energy.",
    heroSubline: "Mi samo vodimo liniju.",
    scroll: "Skroluj da zapocnes",
    workIndex: "01 / Odabrani radovi",
    workTitle: "Koza pamti.",
    workBody: "Svaki rad nastaje iz razgovora, pokreta i karaktera osobe koja ga nosi.",
    craftIndex: "02 / Proces",
    craftTitle: "Ne pratimo trendove. Ostavljamo tragove.",
    craftBody: "Od prve linije do poslednjeg detalja, rad je miran, precizan i lican.",
    pathsIndex: "03 / Tvoj sledeci korak",
    pathsTitle: "Pocnimo od ideje.",
    consult: "Konsultacija",
    consultMeta: "15 min besplatno",
    consultAction: "Izaberi termin",
    inquiry: "Upit",
    inquiryMeta: "Vec imas ideju?",
    inquiryAction: "Posalji ideju",
    finale: "Tvoja koza. Tvoja prica.",
    finalAction: "Rezervisi termin",
  },
  en: {
    nav: { work: "Work", process: "Process", booking: "Booking", reserve: "Book now" },
    heroLine: "Ink is energy.",
    heroSubline: "We simply guide the line.",
    scroll: "Scroll to begin",
    workIndex: "01 / Selected work",
    workTitle: "Skin remembers.",
    workBody: "Every piece begins with conversation, movement and the character of the person wearing it.",
    craftIndex: "02 / Process",
    craftTitle: "We don't follow trends. We leave marks.",
    craftBody: "From the first line to the final detail, the work is calm, precise and personal.",
    pathsIndex: "03 / Your next step",
    pathsTitle: "Let's start with the idea.",
    consult: "Consultation",
    consultMeta: "15 min free",
    consultAction: "Choose a time",
    inquiry: "Inquiry",
    inquiryMeta: "Already have an idea?",
    inquiryAction: "Send your idea",
    finale: "Your skin. Your story.",
    finalAction: "Book a session",
  },
  de: {
    nav: { work: "Arbeiten", process: "Prozess", booking: "Termine", reserve: "Termin" },
    heroLine: "Ink is energy.",
    heroSubline: "Wir fuehren nur die Linie.",
    scroll: "Scrollen zum Start",
    workIndex: "01 / Ausgewaehlte Arbeiten",
    workTitle: "Haut erinnert sich.",
    workBody: "Jedes Motiv entsteht aus Gespraech, Bewegung und dem Charakter der Person, die es traegt.",
    craftIndex: "02 / Prozess",
    craftTitle: "Wir folgen keinen Trends. Wir hinterlassen Spuren.",
    craftBody: "Von der ersten Linie bis zum letzten Detail ist die Arbeit ruhig, praezise und persoenlich.",
    pathsIndex: "03 / Dein naechster Schritt",
    pathsTitle: "Beginnen wir mit der Idee.",
    consult: "Beratung",
    consultMeta: "15 Min kostenlos",
    consultAction: "Termin waehlen",
    inquiry: "Anfrage",
    inquiryMeta: "Schon eine Idee?",
    inquiryAction: "Idee senden",
    finale: "Deine Haut. Deine Geschichte.",
    finalAction: "Termin buchen",
  },
} as const;

export const portfolio = [
  { src: "/media/DSC04808.jpeg", alt: "Blackwork tattoo detail", className: "tunnel-card tunnel-card--one", number: "001" },
  { src: "/media/IMG_8123.jpeg", alt: "Dropz Tattoo finished piece", className: "tunnel-card tunnel-card--two", number: "002" },
  { src: "/media/IMG_5691.jpeg", alt: "Fine tattoo detail", className: "tunnel-card tunnel-card--three", number: "003" },
  { src: "/media/IMG_2288.jpeg", alt: "Custom tattoo composition", className: "tunnel-card tunnel-card--four", number: "004" },
  { src: "/media/IMG_0941.jpeg", alt: "Dropz Tattoo artwork", className: "tunnel-card tunnel-card--five", number: "005" },
  { src: "/media/FullSizeRender.jpeg", alt: "Dropz Tattoo line work", className: "tunnel-card tunnel-card--six", number: "006" },
  { src: "/media/IMG_0451.jpeg", alt: "Detailed tattoo shading", className: "tunnel-card tunnel-card--seven", number: "007" },
  { src: "/media/IMG_0617.jpeg", alt: "Custom blackwork piece", className: "tunnel-card tunnel-card--eight", number: "008" },
  { src: "/media/IMG_1098.jpeg", alt: "Dropz Tattoo composition", className: "tunnel-card tunnel-card--nine", number: "009" },
  { src: "/media/IMG_4676.jpeg", alt: "Fine line tattoo detail", className: "tunnel-card tunnel-card--ten", number: "010" },
] as const;
