export type Locale = "sr" | "en" | "de";

export const locales: Locale[] = ["sr", "en", "de"];

export const copy = {
  sr: {
    nav: { work: "Rad", process: "Proces", portfolio: "Portfolio", education: "Edukacija", aftercare: "Nega", booking: "Termini", reserve: "Rezerviši", account: "Nalog" },
    heroLine: "Ink is energy.",
    heroSubline: "Preciznost je jedino pravilo.",
    heroBook: "Zakaži termin",
    heroCall: "Pozovi studio",
    scroll: "Skroluj da započneš",
    workIndex: "01 / Odabrani radovi",
    workTitle: "Koža pamti.",
    workBody: "Svaki rad nastaje iz razgovora, pokreta i karaktera osobe koja ga nosi.",
    workAll: "Svi",
    craftIndex: "02 / Proces",
    craftTitle: "Ne pratimo trendove. Ostavljamo tragove.",
    craftBody: "Od prve linije do poslednjeg detalja, rad je miran, precizan i ličan.",
    processIndex: "03 / Kako radimo",
    processTitle: "Od ideje do kože.",
    processSteps: [
      { title: "Konsultacija", body: "Kratak razgovor o ideji, mestu i veličini. Besplatno i bez obaveze." },
      { title: "Dizajn", body: "Crtamo motiv samo za tebe. Korekcije dok linija ne legne savršeno." },
      { title: "Sesija", body: "Miran, precizan rad u sterilnom studiju. Pauze kad su ti potrebne." },
      { title: "Nega", body: "Detaljna uputstva i kontrola zarastanja. Tu smo i posle." },
    ],
    voicesIndex: "04 / Utisci",
    voicesTitle: "Koža govori.",
    voices: [
      { quote: "Došao sam sa idejom, otišao sa pričom na ruci. Svaki detalj je promišljen.", author: "Marko — Niš" },
      { quote: "Prvi tattoo, nula stresa. Sve objašnjeno, sve čisto, rezultat savršen.", author: "Jelena — Beograd" },
      { quote: "Cover-up koji je prevazišao sva očekivanja. Majstor linije.", author: "Stefan — Leskovac" },
    ],
    eduIndex: "05 / Edukacija",
    eduTitle: "Zanat se prenosi.",
    eduBody: "Nauči tetoviranje u profesionalnom studiju — od prvih linija na veštačkoj koži do rada na modelima uz mentora.",
    eduStart: { name: "START", meta: "6 dana · 800€", desc: "Prvi koraci: mašinica, higijena, vežbe na veštačkoj koži." },
    eduPro: { name: "PRO", meta: "2 meseca · 2.500€", desc: "Mentorski program: od veštačke kože do rada na modelima." },
    eduAction: "Saznaj više o obukama",
    aftercareIndex: "Nega tetovaže",
    aftercareTitle: "Nega je pola tetovaže.",
    aftercareBody: "Kako paziš na tetovažu prvih par nedelja odlučuje kako će izgledati godinama. Napisali smo jasno uputstvo — korak po korak.",
    aftercareTips: [
      "Prvi zavoj skidaš po dogovoru — pereš čistim rukama, blagim sapunom.",
      "Prva nedelja: tanak sloj kreme, bez čačkanja krastica.",
      "Bez sunca, bazena i sauna dok potpuno ne zaraste.",
    ],
    aftercareAction: "Pročitaj uputstvo za negu",
    pathsIndex: "06 / Tvoj sledeći korak",
    pathsTitle: "Počnimo od ideje.",
    consult: "Konsultacija",
    consultMeta: "15 min besplatno",
    consultAction: "Izaberi termin",
    inquiry: "Upit",
    inquiryMeta: "Već imaš ideju?",
    inquiryAction: "Pošalji ideju",
    bookingIndex: "07 / Termini",
    bookingTitle: "Rezerviši svoje mesto.",
    bookingBody: "Izaberi termin za besplatnu konsultaciju. Konsultacije su ponedeljkom (osim po dogovoru). Javljamo se u roku od 24h.",
    bookingForm: {
      name: "Ime i prezime",
      contact: "Email ili telefon",
      consultNotice: "Konsultacija je besplatna i traje kratko. Ukoliko se dogovorimo, depozit se ostavlja odmah, na licu mesta.",
      note: "Opis ideje (opciono)",
      notePlaceholder: "Motiv, mesto na telu, veličina...",
      date: "Datum",
      time: "Vreme",
      pickDate: "Prvo izaberi datum",
      closed: "Slobodni dani su istaknuti u kalendaru",
      noSlots: "Nema slobodnih termina za ovaj dan",
      submit: "Pošalji zahtev",
      missing: "Popuni ime, kontakt, datum i vreme.",
      success: "Zahtev za termin je primljen. Uskoro će ti se javiti neko iz studija.",
      fallback: "Ili piši direktno na",
      prevMonth: "Prethodni mesec",
      nextMonth: "Sledeći mesec",
    },
    finale: "Tvoja koža. Tvoja priča.",
    finalAction: "Rezerviši termin",
  },
  en: {
    nav: { work: "Work", process: "Process", portfolio: "Portfolio", education: "Education", aftercare: "Aftercare", booking: "Booking", reserve: "Book now", account: "Account" },
    heroLine: "Ink is energy.",
    heroSubline: "Precision is the only rule.",
    heroBook: "Book a session",
    heroCall: "Call the studio",
    scroll: "Scroll to begin",
    workIndex: "01 / Selected work",
    workTitle: "Skin remembers.",
    workBody: "Every piece begins with conversation, movement and the character of the person wearing it.",
    workAll: "All",
    craftIndex: "02 / Process",
    craftTitle: "We don't follow trends. We leave marks.",
    craftBody: "From the first line to the final detail, the work is calm, precise and personal.",
    processIndex: "03 / How we work",
    processTitle: "From idea to skin.",
    processSteps: [
      { title: "Consultation", body: "A short talk about the idea, placement and size. Free, no strings attached." },
      { title: "Design", body: "We draw the piece just for you. Revisions until the line sits perfectly." },
      { title: "Session", body: "Calm, precise work in a sterile studio. Breaks whenever you need them." },
      { title: "Aftercare", body: "Detailed instructions and healing check-ins. We're here afterwards too." },
    ],
    voicesIndex: "04 / Voices",
    voicesTitle: "Skin speaks.",
    voices: [
      { quote: "Came with an idea, left with a story on my arm. Every detail considered.", author: "Marko — Nis" },
      { quote: "First tattoo, zero stress. Everything explained, everything clean, perfect result.", author: "Jelena — Belgrade" },
      { quote: "A cover-up beyond all expectations. Master of the line.", author: "Stefan — Leskovac" },
    ],
    eduIndex: "05 / Education",
    eduTitle: "The craft is passed on.",
    eduBody: "Learn tattooing in a professional studio — from the first lines on synthetic skin to working on models under a mentor.",
    eduStart: { name: "START", meta: "6 days · 800€", desc: "First steps: the machine, hygiene, practice on synthetic skin." },
    eduPro: { name: "PRO", meta: "2 months · 2.500€", desc: "Mentorship program: from synthetic skin to working on models." },
    eduAction: "Learn more about the courses",
    aftercareIndex: "Aftercare",
    aftercareTitle: "Aftercare is half the tattoo.",
    aftercareBody: "How you treat a fresh tattoo in the first weeks decides how it looks for years. We wrote a clear, step-by-step guide.",
    aftercareTips: [
      "Remove the first wrap as advised — wash with clean hands and mild soap.",
      "First week: a thin layer of cream, never pick the scabs.",
      "No sun, pools or saunas until it has fully healed.",
    ],
    aftercareAction: "Read the aftercare guide",
    pathsIndex: "06 / Your next step",
    pathsTitle: "Let's start with the idea.",
    consult: "Consultation",
    consultMeta: "15 min free",
    consultAction: "Choose a time",
    inquiry: "Inquiry",
    inquiryMeta: "Already have an idea?",
    inquiryAction: "Send your idea",
    bookingIndex: "07 / Booking",
    bookingTitle: "Reserve your spot.",
    bookingBody: "Pick a slot for a free consultation. Consultations are on Mondays (or by arrangement). We reply within 24h.",
    bookingForm: {
      name: "Full name",
      contact: "Email or phone",
      consultNotice: "The consultation is free and quick. If we agree to proceed, the deposit is paid on the spot, in person.",
      note: "Describe your idea (optional)",
      notePlaceholder: "Motif, placement, size...",
      date: "Date",
      time: "Time",
      pickDate: "Pick a date first",
      closed: "Open days are highlighted in the calendar",
      noSlots: "No available slots for this day",
      submit: "Send request",
      missing: "Fill in name, contact, date and time.",
      success: "Your booking request has been received. Someone from the studio will get in touch soon.",
      fallback: "Or write directly to",
      prevMonth: "Previous month",
      nextMonth: "Next month",
    },
    finale: "Your skin. Your story.",
    finalAction: "Book a session",
  },
  de: {
    nav: { work: "Arbeiten", process: "Prozess", portfolio: "Portfolio", education: "Ausbildung", aftercare: "Pflege", booking: "Termine", reserve: "Termin", account: "Konto" },
    heroLine: "Ink is energy.",
    heroSubline: "Praezision ist die einzige Regel.",
    heroBook: "Termin buchen",
    heroCall: "Studio anrufen",
    scroll: "Scrollen zum Start",
    workIndex: "01 / Ausgewaehlte Arbeiten",
    workTitle: "Haut erinnert sich.",
    workBody: "Jedes Motiv entsteht aus Gespraech, Bewegung und dem Charakter der Person, die es traegt.",
    workAll: "Alle",
    craftIndex: "02 / Prozess",
    craftTitle: "Wir folgen keinen Trends. Wir hinterlassen Spuren.",
    craftBody: "Von der ersten Linie bis zum letzten Detail ist die Arbeit ruhig, praezise und persoenlich.",
    processIndex: "03 / So arbeiten wir",
    processTitle: "Von der Idee zur Haut.",
    processSteps: [
      { title: "Beratung", body: "Kurzes Gespraech ueber Idee, Stelle und Groesse. Kostenlos und unverbindlich." },
      { title: "Design", body: "Wir zeichnen das Motiv nur fuer dich. Korrekturen, bis die Linie perfekt sitzt." },
      { title: "Session", body: "Ruhige, praezise Arbeit im sterilen Studio. Pausen, wann immer du sie brauchst." },
      { title: "Pflege", body: "Ausfuehrliche Anleitung und Heilungskontrolle. Wir sind auch danach da." },
    ],
    voicesIndex: "04 / Stimmen",
    voicesTitle: "Haut spricht.",
    voices: [
      { quote: "Mit einer Idee gekommen, mit einer Geschichte am Arm gegangen. Jedes Detail durchdacht.", author: "Marko — Nis" },
      { quote: "Erstes Tattoo, null Stress. Alles erklaert, alles sauber, perfektes Ergebnis.", author: "Jelena — Belgrad" },
      { quote: "Ein Cover-up jenseits aller Erwartungen. Meister der Linie.", author: "Stefan — Leskovac" },
    ],
    eduIndex: "05 / Ausbildung",
    eduTitle: "Das Handwerk wird weitergegeben.",
    eduBody: "Lerne Taetowieren in einem professionellen Studio — von den ersten Linien auf Kunsthaut bis zur Arbeit an Modellen unter Anleitung.",
    eduStart: { name: "START", meta: "6 Tage · 800€", desc: "Erste Schritte: Maschine, Hygiene, Uebungen auf Kunsthaut." },
    eduPro: { name: "PRO", meta: "2 Monate · 2.500€", desc: "Mentoring-Programm: von Kunsthaut bis zur Arbeit an Modellen." },
    eduAction: "Mehr ueber die Kurse",
    aftercareIndex: "Pflege",
    aftercareTitle: "Pflege ist die halbe Taetowierung.",
    aftercareBody: "Wie du ein frisches Tattoo in den ersten Wochen behandelst, entscheidet, wie es jahrelang aussieht. Wir haben eine klare Schritt-fuer-Schritt-Anleitung geschrieben.",
    aftercareTips: [
      "Ersten Verband nach Absprache abnehmen — mit sauberen Haenden und milder Seife waschen.",
      "Erste Woche: eine duenne Schicht Creme, niemals an den Krusten kratzen.",
      "Keine Sonne, kein Schwimmbad, keine Sauna bis alles verheilt ist.",
    ],
    aftercareAction: "Zur Pflegeanleitung",
    pathsIndex: "06 / Dein naechster Schritt",
    pathsTitle: "Beginnen wir mit der Idee.",
    consult: "Beratung",
    consultMeta: "15 Min kostenlos",
    consultAction: "Termin waehlen",
    inquiry: "Anfrage",
    inquiryMeta: "Schon eine Idee?",
    inquiryAction: "Idee senden",
    bookingIndex: "07 / Termine",
    bookingTitle: "Sichere dir deinen Platz.",
    bookingBody: "Waehle einen Termin fuer eine kostenlose Beratung. Beratungen finden montags statt (oder nach Vereinbarung). Antwort innerhalb von 24h.",
    bookingForm: {
      name: "Vor- und Nachname",
      contact: "Email oder Telefon",
      consultNotice: "Die Beratung ist kostenlos und kurz. Falls wir uns einigen, wird die Anzahlung sofort vor Ort bezahlt.",
      note: "Beschreibe deine Idee (optional)",
      notePlaceholder: "Motiv, Koerperstelle, Groesse...",
      date: "Datum",
      time: "Uhrzeit",
      pickDate: "Waehle zuerst ein Datum",
      closed: "Freie Tage sind im Kalender hervorgehoben",
      noSlots: "Keine freien Termine an diesem Tag",
      submit: "Anfrage senden",
      missing: "Bitte Name, Kontakt, Datum und Uhrzeit ausfuellen.",
      success: "Deine Terminanfrage wurde empfangen. Jemand aus dem Studio meldet sich bald bei dir.",
      fallback: "Oder schreib direkt an",
      prevMonth: "Vorheriger Monat",
      nextMonth: "Naechster Monat",
    },
    finale: "Deine Haut. Deine Geschichte.",
    finalAction: "Termin buchen",
  },
} as const;

export const portfolio = [
  { src: "/media/DSC04808.jpeg", alt: "Blackwork tattoo detail", className: "tunnel-card tunnel-card--one", number: "001" },
  { src: "/media/IMG_8123.jpeg", alt: "Dropz Tattoo finished piece", className: "tunnel-card tunnel-card--two", number: "002" },
  { src: "/media/IMG_5691.jpeg", alt: "Fine tattoo detail", className: "tunnel-card tunnel-card--three", number: "003" },
  { src: "/media/IMG_2288.jpeg", alt: "Custom tattoo composition", className: "tunnel-card tunnel-card--four", number: "004" },
  { src: "/media/IMG_0941.jpeg", alt: "Dropz Tattoo artwork", className: "tunnel-card tunnel-card--five", number: "005" },
  { src: "/media/FullSizeRender.jpeg", alt: "Dropz Tattoo line work", className: "tunnel-card tunnel-card--six", number: "006" },
  { src: "/media/IMG_0451.jpeg", alt: "Detailed tattoo shading", className: "tunnel-card tunnel-card--seven", number: "007" },
  { src: "/media/IMG_0617.jpeg", alt: "Custom blackwork piece", className: "tunnel-card tunnel-card--eight", number: "008" },
  { src: "/media/IMG_1098.jpeg", alt: "Dropz Tattoo composition", className: "tunnel-card tunnel-card--nine", number: "009" },
  { src: "/media/IMG_4676.jpeg", alt: "Fine line tattoo detail", className: "tunnel-card tunnel-card--ten", number: "010" },
] as const;
