export type Locale = "sr" | "en" | "de";

export const locales: Locale[] = ["sr", "en", "de"];

export const copy = {
  sr: {
    nav: { work: "Rad", process: "Proces", booking: "Termini", reserve: "Rezervisi" },
    heroLine: "Ink is energy.",
    heroSubline: "Mi samo vodimo liniju.",
    scroll: "Skroluj da zapocnes",
    workIndex: "01 / Odabrani radovi",
    workTitle: "Koza pamti.",
    workBody: "Svaki rad nastaje iz razgovora, pokreta i karaktera osobe koja ga nosi.",
    craftIndex: "02 / Proces",
    craftTitle: "Ne pratimo trendove. Ostavljamo tragove.",
    craftBody: "Od prve linije do poslednjeg detalja, rad je miran, precizan i lican.",
    processIndex: "03 / Kako radimo",
    processTitle: "Od ideje do koze.",
    processSteps: [
      { title: "Konsultacija", body: "Kratak razgovor o ideji, mestu i velicini. Besplatno i bez obaveze." },
      { title: "Dizajn", body: "Crtamo motiv samo za tebe. Korekcije dok linija ne legne savrseno." },
      { title: "Sesija", body: "Miran, precizan rad u sterilnom studiju. Pauze kad su ti potrebne." },
      { title: "Nega", body: "Detaljna uputstva i kontrola zarastanja. Tu smo i posle." },
    ],
    voicesIndex: "04 / Utisci",
    voicesTitle: "Koza govori.",
    voices: [
      { quote: "Dosao sam sa idejom, otisao sa pricom na ruci. Svaki detalj je promisljen.", author: "Marko — Nis" },
      { quote: "Prvi tattoo, nula stresa. Sve objasnjeno, sve cisto, rezultat savrsen.", author: "Jelena — Beograd" },
      { quote: "Cover-up koji je prevazisao sva ocekivanja. Majstor linije.", author: "Stefan — Leskovac" },
    ],
    pathsIndex: "05 / Tvoj sledeci korak",
    pathsTitle: "Pocnimo od ideje.",
    consult: "Konsultacija",
    consultMeta: "15 min besplatno",
    consultAction: "Izaberi termin",
    inquiry: "Upit",
    inquiryMeta: "Vec imas ideju?",
    inquiryAction: "Posalji ideju",
    bookingIndex: "06 / Termini",
    bookingTitle: "Rezervisi svoje mesto.",
    bookingBody: "Izaberi dan i vreme koje ti odgovara. Radimo utorak - subota, 11-19h. Javljamo se u roku od 24h.",
    bookingForm: {
      name: "Ime i prezime",
      contact: "Email ili telefon",
      type: "Tip termina",
      typeConsult: "Konsultacija · 15 min",
      typeSession: "Sesija",
      note: "Opis ideje (opciono)",
      notePlaceholder: "Motiv, mesto na telu, velicina...",
      date: "Datum",
      time: "Vreme",
      pickDate: "Prvo izaberi datum",
      closed: "Nedelja i ponedeljak — zatvoreno",
      submit: "Posalji zahtev",
      missing: "Popuni ime, kontakt, datum i vreme.",
      success: "Zahtev je spreman u tvom email programu — samo posalji. Odgovaramo u roku od 24h.",
      fallback: "Ili pisi direktno na",
      prevMonth: "Prethodni mesec",
      nextMonth: "Sledeci mesec",
    },
    finale: "Tvoja koza. Tvoja prica.",
    finalAction: "Rezervisi termin",
  },
  en: {
    nav: { work: "Work", process: "Process", booking: "Booking", reserve: "Book now" },
    heroLine: "Ink is energy.",
    heroSubline: "We simply guide the line.",
    scroll: "Scroll to begin",
    workIndex: "01 / Selected work",
    workTitle: "Skin remembers.",
    workBody: "Every piece begins with conversation, movement and the character of the person wearing it.",
    craftIndex: "02 / Process",
    craftTitle: "We don't follow trends. We leave marks.",
    craftBody: "From the first line to the final detail, the work is calm, precise and personal.",
    processIndex: "03 / How we work",
    processTitle: "From idea to skin.",
    processSteps: [
      { title: "Consultation", body: "A short talk about the idea, placement and size. Free, no strings attached." },
      { title: "Design", body: "We draw the piece just for you. Revisions until the line sits perfectly." },
      { title: "Session", body: "Calm, precise work in a sterile studio. Breaks whenever you need them." },
      { title: "Aftercare", body: "Detailed instructions and healing check-ins. We're here afterwards too." },
    ],
    voicesIndex: "04 / Voices",
    voicesTitle: "Skin speaks.",
    voices: [
      { quote: "Came with an idea, left with a story on my arm. Every detail considered.", author: "Marko — Nis" },
      { quote: "First tattoo, zero stress. Everything explained, everything clean, perfect result.", author: "Jelena — Belgrade" },
      { quote: "A cover-up beyond all expectations. Master of the line.", author: "Stefan — Leskovac" },
    ],
    pathsIndex: "05 / Your next step",
    pathsTitle: "Let's start with the idea.",
    consult: "Consultation",
    consultMeta: "15 min free",
    consultAction: "Choose a time",
    inquiry: "Inquiry",
    inquiryMeta: "Already have an idea?",
    inquiryAction: "Send your idea",
    bookingIndex: "06 / Booking",
    bookingTitle: "Reserve your spot.",
    bookingBody: "Pick a day and time that suits you. Open Tuesday - Saturday, 11am-7pm. We reply within 24h.",
    bookingForm: {
      name: "Full name",
      contact: "Email or phone",
      type: "Appointment type",
      typeConsult: "Consultation · 15 min",
      typeSession: "Session",
      note: "Describe your idea (optional)",
      notePlaceholder: "Motif, placement, size...",
      date: "Date",
      time: "Time",
      pickDate: "Pick a date first",
      closed: "Sunday and Monday — closed",
      submit: "Send request",
      missing: "Fill in name, contact, date and time.",
      success: "Your request is ready in your email app — just hit send. We reply within 24h.",
      fallback: "Or write directly to",
      prevMonth: "Previous month",
      nextMonth: "Next month",
    },
    finale: "Your skin. Your story.",
    finalAction: "Book a session",
  },
  de: {
    nav: { work: "Arbeiten", process: "Prozess", booking: "Termine", reserve: "Termin" },
    heroLine: "Ink is energy.",
    heroSubline: "Wir fuehren nur die Linie.",
    scroll: "Scrollen zum Start",
    workIndex: "01 / Ausgewaehlte Arbeiten",
    workTitle: "Haut erinnert sich.",
    workBody: "Jedes Motiv entsteht aus Gespraech, Bewegung und dem Charakter der Person, die es traegt.",
    craftIndex: "02 / Prozess",
    craftTitle: "Wir folgen keinen Trends. Wir hinterlassen Spuren.",
    craftBody: "Von der ersten Linie bis zum letzten Detail ist die Arbeit ruhig, praezise und persoenlich.",
    processIndex: "03 / So arbeiten wir",
    processTitle: "Von der Idee zur Haut.",
    processSteps: [
      { title: "Beratung", body: "Kurzes Gespraech ueber Idee, Stelle und Groesse. Kostenlos und unverbindlich." },
      { title: "Design", body: "Wir zeichnen das Motiv nur fuer dich. Korrekturen, bis die Linie perfekt sitzt." },
      { title: "Session", body: "Ruhige, praezise Arbeit im sterilen Studio. Pausen, wann immer du sie brauchst." },
      { title: "Pflege", body: "Ausfuehrliche Anleitung und Heilungskontrolle. Wir sind auch danach da." },
    ],
    voicesIndex: "04 / Stimmen",
    voicesTitle: "Haut spricht.",
    voices: [
      { quote: "Mit einer Idee gekommen, mit einer Geschichte am Arm gegangen. Jedes Detail durchdacht.", author: "Marko — Nis" },
      { quote: "Erstes Tattoo, null Stress. Alles erklaert, alles sauber, perfektes Ergebnis.", author: "Jelena — Belgrad" },
      { quote: "Ein Cover-up jenseits aller Erwartungen. Meister der Linie.", author: "Stefan — Leskovac" },
    ],
    pathsIndex: "05 / Dein naechster Schritt",
    pathsTitle: "Beginnen wir mit der Idee.",
    consult: "Beratung",
    consultMeta: "15 Min kostenlos",
    consultAction: "Termin waehlen",
    inquiry: "Anfrage",
    inquiryMeta: "Schon eine Idee?",
    inquiryAction: "Idee senden",
    bookingIndex: "06 / Termine",
    bookingTitle: "Sichere dir deinen Platz.",
    bookingBody: "Waehle Tag und Uhrzeit, die dir passen. Geoeffnet Dienstag - Samstag, 11-19 Uhr. Antwort innerhalb von 24h.",
    bookingForm: {
      name: "Vor- und Nachname",
      contact: "Email oder Telefon",
      type: "Terminart",
      typeConsult: "Beratung · 15 Min",
      typeSession: "Session",
      note: "Beschreibe deine Idee (optional)",
      notePlaceholder: "Motiv, Koerperstelle, Groesse...",
      date: "Datum",
      time: "Uhrzeit",
      pickDate: "Waehle zuerst ein Datum",
      closed: "Sonntag und Montag — geschlossen",
      submit: "Anfrage senden",
      missing: "Bitte Name, Kontakt, Datum und Uhrzeit ausfuellen.",
      success: "Deine Anfrage liegt in deinem Email-Programm bereit — einfach absenden. Antwort innerhalb von 24h.",
      fallback: "Oder schreib direkt an",
      prevMonth: "Vorheriger Monat",
      nextMonth: "Naechster Monat",
    },
    finale: "Deine Haut. Deine Geschichte.",
    finalAction: "Termin buchen",
  },
} as const;

export const portfolio = [
  { src: "/media/DSC04808.jpeg", alt: "Blackwork tattoo detail", className: "tunnel-card tunnel-card--one", number: "001" },
  { src: "/media/IMG_8123.jpeg", alt: "Dropz Tattoo finished piece", className: "tunnel-card tunnel-card--two", number: "002" },
  { src: "/media/IMG_5691.jpeg", alt: "Fine tattoo detail", className: "tunnel-card tunnel-card--three", number: "003" },
  { src: "/media/IMG_2288.jpeg", alt: "Custom tattoo composition", className: "tunnel-card tunnel-card--four", number: "004" },
  { src: "/media/IMG_0941.jpeg", alt: "Dropz Tattoo artwork", className: "tunnel-card tunnel-card--five", number: "005" },
  { src: "/media/FullSizeRender.jpeg", alt: "Dropz Tattoo line work", className: "tunnel-card tunnel-card--six", number: "006" },
  { src: "/media/IMG_0451.jpeg", alt: "Detailed tattoo shading", className: "tunnel-card tunnel-card--seven", number: "007" },
  { src: "/media/IMG_0617.jpeg", alt: "Custom blackwork piece", className: "tunnel-card tunnel-card--eight", number: "008" },
  { src: "/media/IMG_1098.jpeg", alt: "Dropz Tattoo composition", className: "tunnel-card tunnel-card--nine", number: "009" },
  { src: "/media/IMG_4676.jpeg", alt: "Fine line tattoo detail", className: "tunnel-card tunnel-card--ten", number: "010" },
] as const;
